//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sats_airdrop_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_principal: String,
    pub last_airdrop_at: DateTime,
    pub total_sats: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
