//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notification_liked_payload")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub notification_id: i32,
    pub by_user_principal: String,
    pub post_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::notification::Entity",
        from = "Column::NotificationId",
        to = "super::notification::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Notification,
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
