//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::notification::Entity as Notification;
pub use super::notification_liked_payload::Entity as NotificationLikedPayload;
pub use super::notification_video_upload_payload::Entity as NotificationVideoUploadPayload;
